import Head from "next/head";
import Swipers from "components/Swipers";
import { SwiperSlide } from "swiper/react";

export default function Hair() {
  return (
    <>
      <Head>
        <title>퓨라셀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Swipers>
        <SwiperSlide>자라나라</SwiperSlide>
        <SwiperSlide>머리머리</SwiperSlide>
      </Swipers>
    </>
  );
}
