import Head from "next/head";
import Swipers from "components/Swipers";
import { SwiperSlide } from "swiper/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>퓨라셀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Swipers>
          <SwiperSlide style={{ background: "greenyellow" }}>
            Slide 1
          </SwiperSlide>
          <SwiperSlide style={{ background: "pink" }}>Slide 2</SwiperSlide>
          <SwiperSlide style={{ background: "green" }}>Slide 3</SwiperSlide>
          <SwiperSlide style={{ background: "hotpink" }}>Slide 4</SwiperSlide>
        </Swipers>
      </main>
    </div>
  );
}
