import Head from "next/head";
import Swipers from "components/Swipers";
import { SwiperSlide } from "swiper/react";

import _ from "styles/main.module.css";
import Page1 from "components/pages/main/Page1";
import MainLayout from "components/layout/MainLayout";

export default function Home() {
  return (
    // <main className={_.main}>
    <MainLayout>
      <Head>
        <title>Hair</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Swipers>
        <SwiperSlide>
          <Page1 />
        </SwiperSlide>
      </Swipers>
    </MainLayout>
    // </main>
  );
}
