import Head from 'next/head';
import Image from 'next/image';
import mainKr from 'public/locales/kr/main';

import tempImage from 'src/image/header/puraxel_logo_basic.svg';

export default function Home() {
  return (
    <div>
      <Head>
        <title>퓨라셀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <body style={{ display: 'grid', gridTemplateRows: '40vh 60vh' }}>
          <div
            style={{
              // background: 'cyan',
              display: 'grid',
              gridTemplateColumns: '2fr 3fr',
            }}
          >
            <div
              style={{
                // background: 'red',
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'center',
                alignItems: 'center',
                // margin: '1rem',
                // gap: '1rem',
              }}
            >
              {/* 폰트 키우기 */}
              <span>{mainKr.title1A}</span>
              <span>{mainKr.title1B}</span>
            </div>
            <div
              style={{
                // background: 'yellow',
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'end',
              }}
            >
              {/* 폰트 키우기 윗줄 */}
              <span>{mainKr.explain1A}</span>
              <span>{mainKr.explain1B}</span>
              {/* 폰트 키우기 아랫줄 */}
              <span>{mainKr.explain1A}</span>
              <span>{mainKr.explain1B}</span>
            </div>
          </div>

          {/* 이미지 꽉 채우기 */}

          <div
            style={{
              display: 'flex',
              // background: 'yellowgreen',
              justifyContent: 'center',
              alignItems: 'center',
              // backgroundImage: `url(${tempImage})`,
            }}
          >
            <Image src={tempImage} alt="temp" />
          </div>
        </body>
      </main>
    </div>
  );
}
