import Head from "next/head";
import Swipers from "components/Swipers";
import MeLayout from "components/layout/MeLayout";
import { SwiperSlide } from "swiper/react";
import Page0 from "components/pages/Me/temp.Page1";
import Page2 from "components/pages/Me/Page2";
import Page3 from "components/pages/Me/Page3";
import Page44 from "components/pages/Me/temp.Page5";
import Oval from "components/Parts/Oval";

export default function Me() {
  return (
    <MeLayout>
      <Head>
        <title>PURAXEL ME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Swipers>
        <Oval startX={0} startY={0} EndX={0} EndY={300} />
        <SwiperSlide>
          {/* <Oval startX={0} startY={0} EndX={0} EndY={300} /> */}
          <Page0 />
        </SwiperSlide>

        <SwiperSlide>
          <Page2 />
          {/* <Oval startX={0} startY={300} EndX={-600} EndY={300} /> */}
        </SwiperSlide>

        <SwiperSlide>
          <Page3 />
          {/* <Oval startX={-600} startY={300} EndX={200} EndY={-300} /> */}
        </SwiperSlide>

        <SwiperSlide>
          <Page44 />
          {/* <Oval startX={200} startY={-300} EndX={-500} EndY={300} /> */}
        </SwiperSlide>
      </Swipers>
    </MeLayout>
  );
}
