import Head from "next/head";
import Swipers from "components/Swipers";
import MeLayout from "components/layout/MeLayout";
import { SwiperSlide } from "swiper/react";
import Page1 from "components/pages/Me/Page1";
import Page2 from "components/pages/Me/Page2";
import Page3 from "components/pages/Me/Page3";
import Page4 from "components/pages/Me/Page4";
import Page5 from "components/pages/puraTech/Page2";
import Oval from "components/Parts/Oval";

export default function Me() {
  return (
    <MeLayout>
      <Head>
        <title>PURAXEL ME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Swipers>
        <SwiperSlide>
          <Page1 />
        </SwiperSlide>

        <SwiperSlide>
          <Page2 />
        </SwiperSlide>

        <SwiperSlide>
          <Page3 />
        </SwiperSlide>

        <SwiperSlide>
          <Page4 />
        </SwiperSlide>

        <SwiperSlide>
          <Page5 />
        </SwiperSlide>
      </Swipers>
    </MeLayout>
  );
}
