import Head from "next/head";
import TechLayout from "components/layout/TechLayout";
import Swipers from "components/Swipers";
import { SwiperSlide } from "swiper/react";
import Page1 from "components/pages/puraTech/Page1";
import Page2 from "components/pages/puraTech/Page2";
import Page3 from "components/pages/puraTech/Page3";
import Page4 from "components/pages/puraTech/Page4";

export default function PuraTech() {
  return (
    <TechLayout>
      <Swipers>
        <Head>
          <title>퓨ㅡ라 테크</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <SwiperSlide>{Page1}</SwiperSlide>
        <SwiperSlide>{Page2}</SwiperSlide>
        <SwiperSlide>{Page3}</SwiperSlide>
        <SwiperSlide>{Page4}</SwiperSlide>
      </Swipers>
    </TechLayout>
  );
}
